// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnuxleoohqpnuhryynmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudXhsZW9vaHFwbnVocnl5bm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODYxMDUsImV4cCI6MjA2MDQ2MjEwNX0.bH02F4VVZpacH4vsbu77aVYCeS4tHswOlwj6FblUD4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);